import "./globals.css";
import localFont from "next/font/local";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { Great_Vibes } from 'next/font/google';

const greatFont = Great_Vibes({ subsets: ['latin'], weight: ['400'] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body   className={`antialiased ${'greatFont.className'} `}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
